services:
  db:
    env_file:
      - .env.dev

  app:
    volumes:
      - ./app:/app/app          
      - ./common.py:/app/common.py  
      - ./pyproject.toml:/app/pyproject.toml
      - ./uv.lock:/app/uv.lock
      - ./entrypoint.sh:/app/entrypoint.sh
    env_file:
      - .env.dev
