services:
  db:
    image: postgres:15
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8080:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}

  docs:
    build:
      context: .
      dockerfile: Dockerfile.docs
    working_dir: /app
    volumes:
      - ./:/app
      - ./CHANGELOG.md:/app/docs/changelog.md
    ports:
      - "8081:8000"

volumes:
  pgdata:
