[project]
name = "contacts-keeper"
version = "0.1.0"
description = "A simple web app to storing contacts"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "faker>=37.4.0",
    "flasgger>=0.9.7.1",
    "flask>=3.1.1",
    "gunicorn>=23.0.0",
    "mkdocs-material>=9.6.16",
    "psycopg2>=2.9.10",
    "python-dotenv>=1.1.1",
]

[dependency-groups]
dev = [
    "commitizen>=4.8.3",
    "mypy>=1.16.1",
    "pre-commit>=4.2.0",
    "ruff>=0.12.0",
]

[tool.pyright]
typeCheckingMode = "basic" 

reportMissingTypeStubs = false
reportMissingImports = true
reportOptionalSubscript = true
reportOptionalMemberAccess = false
reportOptionalCall = false
reportGeneralTypeIssues = true
reportArgumentType = true

exclude = [
  "**/__pycache__",
  "**/node_modules",
  "**/dist",
  "**/.venv",
  "**/tests"
]

[tool.mypy]
disallow_untyped_defs = false
disallow_incomplete_defs = false
check_untyped_defs = true
ignore_missing_imports = true
warn_return_any = false
warn_unused_ignores = true
allow_untyped_globals = true
pretty = true

[tool.ruff]
exclude = [
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
    ".vscode",
    "__pypackages__",
    "venv",
    "__init__.py",
]

line-length = 79
indent-width = 4

[tool.ruff.lint]
fixable = ["ALL"]
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.commitizen]
name = "cz_customize"
update_changelog_on_bump = true 
changelog_file = "CHANGELOG.md" 
version = "1.0.0"
tag_format = "v$version"
version_files = [
    "pyproject.toml:tool.commitizen.version"
]
allow_bump_on_tag = true

[tool.commitizen.customize]
bump_message = "chore(release): v$current_version → v$new_version"
message_template = "{{change_type}}: {{message}}"
example = "ci: configure GitHub Actions"
schema = "<type>: <message>"
schema_pattern = "^(ci|chore|feat|fix|refactor|test|bump|perf|docs)(\\(.*\\))?:\\s.+"
bump_pattern = "^(break|feat|fix|initial|first)"
commit_parser = "^(?P<change_type>ci|chore|feat|test|bump|fix|refactor|perf|docs)(\\(.*\\))?:\\s(?P<message>.+)"
changelog_pattern = "^(ci|chore|feat|fix|refactor|test|perf|docs)(\\(.*\\))?:"
change_type_order = [
  "BREAKING CHANGE",
  "Features",
  "Bug Fixes",
  "CI",
  "Chores",
  "Refactoring",
  "Documentation",
  "Performance",
  "Test"
]

[tool.commitizen.customize.bump_map]
break = "MAJOR"
feat = "MINOR"
fix = "PATCH"
initial = "MAJOR"
first = "MAJOR"

[tool.commitizen.customize.change_type_map]
feat = "Features"
fix = "Bug fixes"
ci = "CI"
chore = "Chores"
docs = "Documentation"
refactor = "Refactoring"
perf = "Performance"
test = "Test"

[[tool.commitizen.customize.questions]]
type = "list"
name = "change_type"
choices = [
  { value = "feat", name = "feat: A new feature" },
  { value = "fix", name = "fix: A bug fix" },
  { value = "ci", name = "ci: Continuous Integration related" },
  { value = "chore", name = "chore: Maintenance or build changes" },
  { value = "docs", name = "docs: Documentation updates" },
  { value = "refactor", name = "refactor: Code restructuring" },
  { value = "perf", name = "perf: Performance improvements" },
  { value = "test", name = "test: Tests" }
]
message = "Select the type of change you are committing"

[[tool.commitizen.customize.questions]]
type = "input"
name = "message"
message = "Enter the commit message"
